# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21b6f9d4e03b090179b4e870d836c24f4a4eb8e2d5bb80d6fd9d877945ebb59107be02b50775f49c4f76e4d9f5367620dabc0a5baee85f0a915a2aaffb0c89e9
  mmf_key: vpqr26eha6rtk9exj87dq9bwxeqzhnq8
  mmf_secret: 9P3AWgpUtGDuTp9HHKSAzRtZzDHEMxmngd7tWGAWUD7
  mmf_access_token: 6b93e1242b1a2c4f7a4331220b3233bae562f1e8
test:
  secret_key_base: 3e8883c29b552baf15ad0eac956cfa2b1e01bcdf460a3fbe07e81329962ecf20679a13ff1bb25cc674834fe87c5884b22bf72f19c87c667460093aab7802d099
  mmf_key: vpqr26eha6rtk9exj87dq9bwxeqzhnq8
  mmf_secret: 9P3AWgpUtGDuTp9HHKSAzRtZzDHEMxmngd7tWGAWUD7
  mmf_access_token: 6b93e1242b1a2c4f7a4331220b3233bae562f1e8
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 3e8883c29b552baf15ad0eac956cfa2b1e01bcdf460a3fbe07e81329962ecf20679a13ff1bb25cc674834fe87c5884b22bf72f19c87c667460093aab7802d099
  mmf_key: vpqr26eha6rtk9exj87dq9bwxeqzhnq8
  mmf_secret: 9P3AWgpUtGDuTp9HHKSAzRtZzDHEMxmngd7tWGAWUD7
  mmf_access_token: 6b93e1242b1a2c4f7a4331220b3233bae562f1e8
